//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioVideo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VideoAudioSalonEntities1 : DbContext
    {
        public VideoAudioSalonEntities1()
            : base("name=VideoAudioSalonEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Catalog> Catalog { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<TechniqueType> TechniqueType { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
